const tintColor = '#2f95dc';

export default {
  tintColor,
  tabIconDefault: '#ccc',
  tabIconSelected: tintColor,
  tabBar: '#fefefe',
  warningBackground: '#EAEB5E',
  warningText: '#666804',
  noticeBackground: tintColor,
  noticeText: '#fff',
  iconDefaultColor: '#ccc',
  borderColor: 'gray',
  flashlightOn: '#ffd099',
  flashlightOff: '#111',
  modalBackground: '#5d7683',
  headerTitleColor: '#000', //'#5d7683',
  scanTransparentColor: 'rgba(93,119,132,0.7)',
  modalTransparentColor: 'rgba(0,0,0,0)',
  listTableOddItemBackgroundColor: '#d6dde0',
  listTableEvenItemBackgroundColor: '#bec8cd',
  labelColor: '#e5eaef',
  overlay: 'rgba(19,30,41,0.8)',
  formBackgroundColor: '#5d7683',
  backgroundLight: "#fff",
  backgroundDark: "#5d7683",
  placeholderTextColor: 'rgba(93, 118, 131, 0.75)',
  inputLabelColor: '#e5eaef',
  messageContentFontColor: '#fff',
  flashMessageSuccess: "#00974c",
  flashMessageDanger:  "#e92e1b",
  flashMessageWarning: "#f38700",
};
